### ISSUE TITLE
Dreams and expectations

### ISSUE THREAD

**Issue by jboxman** [chingu-voyage3/bears-11#5]
Let's each answer the following questions, to get a better idea of where we want to go together.

- How do you think this experience will benefit you?
- What is your coding experience?
- How many hours can you devote to this project per week?
- Will you be available for twice weekly check-ins? (I'll need to schedule these for future weeks.)
- Do you have a preference for video chat, teleconference, or text based check-ins?
- What's a fun fact about you?

**Comment by mojicaj** [comment]
- I think this experience will help me grow as a developer.  It'll help me to start thinking about my code in terms of how others will view or approach it and better prepare me to enter the field.  It'll show me areas I need to work on to be a better developer.

- I describe my coding experience is periodic experimentation.  I took two semesters of Java in the early 2000's but never did anything with it.  Then I learned HTML/CSS and built some Wordpress sites.  I played around with PHP a little but only got as far as being able to mess around with hooks in Wordpress.  Also looked at Ruby for a bit but didn't go to far with it either.

- I can pretty much guarantee 10 hours a week.  Anything over that will vary from week to week but I try to put in ~20 hours per week.

- I can do the check-ins during any of the times I listed in the availability thread.

- no preference just would need to know what to use for video if anything other than skype.

- Fun fact: I'm an infoholic and try to know at least a little about as much as possible.  I wish I could fast scan info like Johnny 5 or download info like in the Matrix.

**Comment by Renestl** [comment]
* I think this experience will grow me as a developer. It will allow me to work with others and bring a project to completion in a group setting. I'm sure my ability to use git will be much better at the end. And since this is a learning experience, it will help me to get more practice learning on the fly, which I assume is needed with ever changing technology.
* My coding experience is still evolving but no longer a revolving door of should I do this. In high school I learned html/css/xhtml and some database that I don't remember the name of. Started a masters in info systems before finally admitting that I really don't like or do well in school. I know enough PHP to play around in Wordpress. Late 2015 I got serious about JavaScript.
* I can promise 10. The ability to do more will vary week to week.
* Yes, but would need to know in advance since my daytime schedule can vary.
* No preference
* mojicaj stole my fun fact about wanting to have all the info :'(  
so... I'd rather read a book than watch TV/movies but can occasionally be lured away to watch Japanese dramas.

**Comment by eolculnamo2** [comment]
- How do you think this experience will benefit you? The biggest benefit
   I anticipate from this project is learning to code collaboratively with
   others who have different preferences and styles. I anticipate great
   learning experiences as we discover ways to delegate the work load and
   create the app in such a way that all four of us can take ownership of it.
   - What is your coding experience? My actual time coding has not been all
   that long. I started last April, but I've coded 20+ hours per week since
   then with FreeCodeCamp and have all my certs.
   - How many hours can you devote to this project per week? At least 10.
   I'd like to give more.
   - Will you be available for twice weekly check-ins? (I'll need to
   schedule these for future weeks.) Absolutely.
   - Do you have a preference for video chat, teleconference, or text based
   check-ins? I'd love to video chat with everyone at least a couple times,
   but I know its hard to coordinate schedules. I'm definitely okay with text
   chats.
   - What's a fun fact about you? I've studied Renaissance Martial
   Arts/Historical European Martial Arts since I was 14. lol

**Comment by jboxman** [comment]
I'll play too.

**How do you think this experience will benefit you?**

Learning project management. Also code reviews and Github workflows.

**What is your coding experience?**

I've been working on fCC on and off for 2 years now. Many years ago, I did some Web development in Perl. At one point, I used Ruby for personal projects.

I've completed most of the fCC projects, except the dungeon crawler and 4 of the final projects.

**How many hours can you devote to this project per week?**

At least 10.

**Will you be available for twice weekly check-ins? (I'll need to schedule these for future weeks.)**

I hope so, or I'm not doing my job.

**Do you have a preference for video chat, teleconference, or text based check-ins?**

Any. In the interests of full disclosure, the idea of calls and video conferencing often unnerve me, but I think it's important.

**What's a fun fact about you?**

I'm left handed.
